In [31]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras

In [32]:
hava_durumu=pd.read_csv("NEM_SICAKLIK.csv")

In [4]:
hava_durumu.head()

NEM  Sıcaklık Hava Durumu
0  68.0      19.6     Bulutlu
1  68.0      19.5     Bulutlu
2  68.0      19.5     Bulutlu
3  68.0      19.5     Bulutlu
4  68.0      19.5     Bulutlu

In [33]:
hava_durumu.keys()

Index(['NEM', 'Sıcaklık', 'Hava Durumu'], dtype='object')

In [34]:
hava_durumu['Hava Durumu'].unique()

array(['Bulutlu', 'Yagmurlu', 'Gunesli'], dtype=object)

In [35]:
factorized_mapping = dict(enumerate(hava_durumu['Hava Durumu'].unique()))
hava_durumu['Hava Durumu'] = pd.factorize(hava_durumu['Hava Durumu'])[0]
print(factorized_mapping)

{0: 'Bulutlu', 1: 'Yagmurlu', 2: 'Gunesli'}


In [36]:
features = hava_durumu[['Sıcaklık','NEM']]
labels = hava_durumu[['Hava Durumu']]

# Train Test Split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.3, random_state=0)
     

In [37]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')  # Çıkış katmanı, üç sınıf için softmax aktivasyon fonksiyonu
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(
    features_train,labels_train,
    epochs=6,
    validation_data=(features_test, labels_test)
    )

Epoch 1/6
85/85 [==============================] - 4s 13ms/step - loss: 1.2476 - accuracy: 0.4438 - val_loss: 0.7889 - val_accuracy: 0.6182
Epoch 2/6
85/85 [==============================] - 1s 6ms/step - loss: 0.6704 - accuracy: 0.7514 - val_loss: 0.5334 - val_accuracy: 0.8381
Epoch 3/6
85/85 [==============================] - 1s 6ms/step - loss: 0.4355 - accuracy: 0.9551 - val_loss: 0.3749 - val_accuracy: 0.9333
Epoch 4/6
85/85 [==============================] - 1s 6ms/step - loss: 0.2825 - accuracy: 0.9803 - val_loss: 0.2244 - val_accuracy: 0.9974
Epoch 5/6
85/85 [==============================] - 1s 8ms/step - loss: 0.1729 - accuracy: 0.9944 - val_loss: 0.1588 - val_accuracy: 0.9654
Epoch 6/6
85/85 [==============================] - 1s 6ms/step - loss: 0.1208 - accuracy: 0.9889 - val_loss: 0.1124 - val_accuracy: 0.9887


In [38]:
predictions = model.predict(features_test)
print(predictions)


37/37 [==============================] - 0s 3ms/step
[[8.3799344e-03 3.1915855e-02 9.5970428e-01]
 [2.6674354e-03 7.7784568e-02 9.1954803e-01]
 [7.4864879e-08 9.3807584e-01 6.1924104e-02]
 ...
 [2.1359404e-03 7.8319609e-02 9.1954446e-01]
 [8.5478169e-01 1.5981877e-05 1.4520226e-01]
 [9.5683599e-01 1.7002985e-06 4.3162271e-02]]


In [39]:
rounded_predictions = [round(prediction[0]) for prediction in predictions]
original_predictions = [factorized_mapping[prediction] for prediction in rounded_predictions]
original_predictions
     

['Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Yagmurlu',
 'Bulutlu',
 'Yagmurlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Yagmurlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Yagmurlu',
 'Yagmurlu',
 'Yagmurlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Yagmurlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Bulutlu',
 'Bulutlu',
 'Yagmurlu',
 'Yagmurlu',
 'Yagmurlu',
 'Bulutlu',

In [40]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(features_train)
X_test_scaled = scaler.transform(features_test)

c:\Users\muri-\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\muri-\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\muri-\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\muri-\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:757: FutureWarning:

In [41]:
test_loss, test_acc = model.evaluate(X_test_scaled, labels_test)
print('Test loss:', test_loss)
print('Test accuracy:', test_acc)

37/37 [==============================] - 1s 5ms/step - loss: 0.8683 - accuracy: 0.8563
Test loss: 0.8682933449745178
Test accuracy: 0.8562770485877991


In [42]:


# Convert the model to the TensorFlow Lite format without quantization
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model to disk
open("C:\\Users\\muri-\\Desktop\\Devre_Tasarım\\weather_model.h", "wb").write(tflite_model)


import os 
basic_model_size = os.path.getsize("weather_model.h")
print("Model is %d bytes" % basic_model_size)
     

INFO:tensorflow:Assets written to: C:\Users\muri-\AppData\Local\Temp\tmpqoujfo5k\assets


INFO:tensorflow:Assets written to: C:\Users\muri-\AppData\Local\Temp\tmpqoujfo5k\assets


Model is 20312 bytes


In [17]:
dosya_yolu = r"C:\Users\muri-\Desktop\Devre_Tasarım\model.h"

# model.h dosyasını oluştur
with open(dosya_yolu, "w") as f:
    f.write("const unsigned char model[] = {\n")
    # model.h dosyasına TensorFlow Lite modelini ekleme
    with open("weather_model.tflite", "rb") as model_file:
        for line in model_file:
            # Bayt dizisini satır satır model.h dosyasına ekleyin
            f.write("    ")
            f.write(", ".join(f"{byte:#04x}" for byte in line))
            f.write(",\n")
    f.write("};")

print(f"{dosya_yolu} dosyası oluşturuldu.")



C:\Users\muri-\Desktop\Devre_Tasarım\model.h dosyası oluşturuldu.


In [43]:
import os
model_h_size = os.path.getsize("weather_model.h")
print(f"Header file, model.h, is {model_h_size:,} bytes.")
print("\nOpen the side panel (refresh if needed). Double click model.h to download the file.")

Header file, model.h, is 20,312 bytes.

Open the side panel (refresh if needed). Double click model.h to download the file.


In [ ]:


# Convert the model to the TensorFlow Lite format without quantization
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model to disk
open("C:\\Users\\muri-\\Desktop\\Devre_Tasarım\\weather_model.h", "wb").write(tflite_model)


import os
basic_model_size = os.path.getsize("weather_model.h")
print("Model is %d bytes" % basic_model_size)
     

INFO:tensorflow:Assets written to: C:\Users\muri-\AppData\Local\Temp\tmpfz0r_btf\assets


INFO:tensorflow:Assets written to: C:\Users\muri-\AppData\Local\Temp\tmpfz0r_btf\assets


Model is 20280 bytes
